# Generate header dependencies during compilation preprocessing.
CPPFLAGS = -MMD
# the usual...
CXXFLAGS = --std=c++20 -O2 -Wall -Wextra -pedantic -Werror

.PHONY: all
all: examples/simple.svg examples/complex.svg examples/dupey.svg

.PHONY: clean
clean:
	rm -f shortestpath.d shortestpath.o shortestpath
	find examples/ -type f \( -name '*.dot' -o -name '*.svg' \) -delete

shortestpath: shortestpath.o
	$(CXX) -o $@ $^

%.svg: %.dot
	dot -Tsvg $^ >$@

%.dot: %.txt shortestpath
	./shortestpath <$< >$@

# Include the make targets that were generated by the implicit %.o rule, which
# will invoke the C++ compiler and pass it the CPPFLAGS preprocessor flags,
# which contain the "-MMD" argument, which produces a *.d file that relates
# sources to header files included by them.
-include *.d
